"""
PAIMANA PredictIQ — Human-in-the-Loop Intervention Recommendation Engine
Module: app.services.intervention_engine
Author: System Architect (SIH 26103)

Core Architectural Governance:
Every recommendation generated by this engine exists strictly to INFORM human decision-makers,
never to replace government authorities or execute autonomous directives.
Each recommendation requires explicit human approval gates, grounded evidence standards,
confidence ratings, and defined approver roles.
"""

import logging
from enum import Enum
from datetime import datetime
from typing import Dict, List, Any, Optional
from pydantic import BaseModel, Field

logger = logging.getLogger("PAIMANA_Backend.InterventionEngine")


class ApprovalStatus(str, Enum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class InterventionPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class InterventionRecommendation(BaseModel):
    """Production schema for grounded human-in-the-loop intervention recommendations."""
    recommendation_id: str
    project_id: str
    priority_score: float = Field(..., ge=0.0, le=100.0)
    priority_level: InterventionPriority
    risk_driver: str
    evidence: str
    recommended_action: str
    expected_objective: str
    review_window: str
    confidence_score: float = Field(..., ge=0.0, le=100.0)
    human_approval_required: bool = True
    approver_role: str
    status: ApprovalStatus = ApprovalStatus.PROPOSED
    reviewer_notes: Optional[str] = None
    reviewed_at: Optional[str] = None
    created_at: str


class InterventionEngine:
    """
    Engine mapping predictive risk drivers to grounded review actions,
    computing multi-factor priority scores, and managing human approval workflows.
    """

    def __init__(self):
        # In-memory store for recommendations & human approval decisions
        self.recommendations_store: Dict[str, InterventionRecommendation] = {}

    def calculate_priority_score(
        self,
        risk_score: float,
        trajectory_status: str,
        budget_cr: float,
        cost_overrun_pct: float,
        schedule_delay_days: float,
        strategic_importance_weight: float = 1.0
    ) -> Tuple[float, InterventionPriority]:
        """
        Calculates multi-factor priority score (0 - 100):
        Score = (0.35 * Risk + 0.25 * Trajectory + 0.20 * FinancialExp + 0.20 * ScheduleSlip) * 100 * Impact
        """
        # Trajectory multiplier
        if trajectory_status.upper() in ["CRITICAL", "ESCALATING"]:
            traj_val = 1.0
        elif trajectory_status.upper() in ["HIGH_RISK", "WATCH"]:
            traj_val = 0.6
        else:
            traj_val = 0.2

        # Financial exposure factor (Normalized to [0, 1])
        financial_exposure_cr = budget_cr * max(0.0, cost_overrun_pct / 100.0)
        fin_factor = min(1.0, financial_exposure_cr / 500.0) # Scale: 500 Cr max norm

        # Schedule slip factor (Normalized to [0, 1])
        slip_factor = min(1.0, max(0.0, schedule_delay_days / 365.0))

        raw_score = (
            0.35 * risk_score +
            0.25 * traj_val +
            0.20 * fin_factor +
            0.20 * slip_factor
        ) * 100.0 * strategic_importance_weight

        priority_score = min(100.0, max(0.0, round(raw_score, 1)))

        if priority_score >= 80.0:
            level = InterventionPriority.CRITICAL
        elif priority_score >= 60.0:
            level = InterventionPriority.HIGH
        elif priority_score >= 40.0:
            level = InterventionPriority.MEDIUM
        else:
            level = InterventionPriority.LOW

        return priority_score, level

    def generate_interventions_for_project(
        self,
        project_id: str,
        prediction_output: Dict[str, Any],
        trajectory_metrics: Dict[str, Any],
        budget_cr: float = 500.0,
        strategic_importance: float = 1.1
    ) -> List[InterventionRecommendation]:
        """
        Maps project risk signals and feature drivers to grounded review actions.
        """
        risk_score = float(prediction_output.get("implementation_risk", 0.50))
        cost_overrun_pct = float(prediction_output.get("predicted_cost_overrun_percentage", 10.0))
        delay_days = float(prediction_output.get("predicted_delay_duration", 90.0))
        traj_state = str(trajectory_metrics.get("current_state", "WATCH"))

        priority_score, priority_level = self.calculate_priority_score(
            risk_score, traj_state, budget_cr, cost_overrun_pct, delay_days, strategic_importance
        )

        now_str = datetime.utcnow().isoformat() + "Z"
        recommendations: List[InterventionRecommendation] = []

        # 1. Milestone Slippage Driver
        ms_rate = float(prediction_output.get("feature_values", {}).get("milestone_slippage_rate", 0.45))
        if ms_rate >= 0.20 or risk_score >= 0.60:
            rec_id = f"REC_{project_id}_MS_{int(datetime.utcnow().timestamp())}"
            rec = InterventionRecommendation(
                recommendation_id=rec_id,
                project_id=project_id,
                priority_score=priority_score,
                priority_level=priority_level,
                risk_driver="Milestone Slippage Rate",
                evidence=f"Milestone slippage rate reached {ms_rate * 100:.1f}% across recent reporting cycles, exceeding the 20.0% governance threshold.",
                recommended_action="Convene a Technical Milestone Performance & Critical Path Audit with executive contractors.",
                expected_objective="Establish revised critical path milestone baselines and allocate site engineering personnel.",
                review_window="3 Days (Executive Escalation Window)",
                confidence_score=92.0,
                human_approval_required=True,
                approver_role="Ministry Project Sanctioning Committee / District Magistrate",
                status=ApprovalStatus.PROPOSED,
                created_at=now_str
            )
            self.recommendations_store[rec_id] = rec
            recommendations.append(rec)

        # 2. Progress Gap / Physical Execution Divergence
        progress_gap = float(prediction_output.get("feature_values", {}).get("progress_gap_pct", 15.0))
        if progress_gap >= 10.0 or delay_days >= 120.0:
            rec_id = f"REC_{project_id}_GAP_{int(datetime.utcnow().timestamp()) + 1}"
            rec = InterventionRecommendation(
                recommendation_id=rec_id,
                project_id=project_id,
                priority_score=round(priority_score * 0.95, 1),
                priority_level=priority_level,
                risk_driver="Persistent Physical Progress Gap",
                evidence=f"Physical progress lags behind elapsed timeline by {progress_gap:.1f}% (Predicted delay duration: {delay_days:.0f} days).",
                recommended_action="Execute On-Site Physical Execution & Resource Mobilization Review.",
                expected_objective="Verify contractor equipment, labor workforce deployment, and material supply chain bottlenecks.",
                review_window="7 Days (Weekly Oversight Review)",
                confidence_score=89.5,
                human_approval_required=True,
                approver_role="Superintending Engineer / Nodal Project Officer",
                status=ApprovalStatus.PROPOSED,
                created_at=now_str
            )
            self.recommendations_store[rec_id] = rec
            recommendations.append(rec)

        # 3. Cost Acceleration / Budget Variance
        if cost_overrun_pct >= 10.0:
            rec_id = f"REC_{project_id}_COST_{int(datetime.utcnow().timestamp()) + 2}"
            rec = InterventionRecommendation(
                recommendation_id=rec_id,
                project_id=project_id,
                priority_score=round(priority_score * 0.90, 1),
                priority_level=priority_level,
                risk_driver="Cost Acceleration & Budget Escalation",
                evidence=f"Predicted cost overrun percentage stands at +{cost_overrun_pct:.1f}% (Financial exposure: ₹{(budget_cr * cost_overrun_pct / 100.0):.2f} Cr).",
                recommended_action="Initiate Financial Expenditure & Revised Cost Estimation Audit.",
                expected_objective="Audit item rate variations, unapproved scope additions, and price escalation clauses.",
                review_window="7 Days (Financial Governance Window)",
                confidence_score=94.0,
                human_approval_required=True,
                approver_role="Financial Advisor / Ministry Finance Committee",
                status=ApprovalStatus.PROPOSED,
                created_at=now_str
            )
            self.recommendations_store[rec_id] = rec
            recommendations.append(rec)

        # Sort by priority score descending
        recommendations.sort(key=lambda x: x.priority_score, reverse=True)
        return recommendations

    def update_human_approval_status(
        self,
        recommendation_id: str,
        new_status: ApprovalStatus,
        reviewer_notes: str,
        reviewer_name: str
    ) -> InterventionRecommendation:
        """
        Updates the human approval status of a recommendation.
        """
        rec = self.recommendations_store.get(recommendation_id)
        if not rec:
            raise KeyError(f"Intervention recommendation {recommendation_id} not found.")

        rec.status = new_status
        rec.reviewer_notes = f"Decision by {reviewer_name}: {reviewer_notes}"
        rec.reviewed_at = datetime.utcnow().isoformat() + "Z"
        logger.info(f"Human Approval Gate Updated: {recommendation_id} set to {new_status} by {reviewer_name}")
        return rec
