import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { Activity, FileText, Globe, Mic, CloudRain, ShieldCheck, Camera, Send, Download, Building2 } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { intelligence, intelligenceBase, encodeFile } from '../api/intelligence';
import { ExpandableChartCard } from '../components/common/ExpandableChartCard';
import { ProjectRecords } from '../components/intelligence/ProjectRecords';
import { LiveVoice } from '../components/intelligence/LiveVoice';
import { getQueue, getReceipts, pauseInspection, restoreQueueBackup, queueInspection, syncQueue } from '../lib/inspectionQueue';

const sections = [ ['documents','Document intelligence',FileText], ['twin','Climate & cost twin',CloudRain], ['satellite','Satellite evidence',Globe], ['uncertainty','Prediction bounds',Activity], ['contractors','InfraScore',Building2], ['field','Field inspection',Camera], ['dispatch','Escalations',Send], ['reports','Executive dossier',Download], ['settings','Connections',ShieldCheck] ] as const;
const inputClass = 'w-full rounded-xl border border-slate-300 bg-white p-3 text-sm text-slate-900';
const buttonClass = 'rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50 hover:bg-blue-800';
const today = new Date().toISOString().slice(0,10);
function JsonView({ value }: { value: unknown }) { return <pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 text-xs leading-6">{JSON.stringify(value,null,2)}</pre>; }
function EvidenceImport({ title, initial, path, onSaved }: {title:string;initial:unknown;path:string;onSaved:()=>void}) {
  const [text,setText]=useState(JSON.stringify(initial,null,2)); const [message,setMessage]=useState(''); const [saved,setSaved]=useState<unknown>(null); const [busy,setBusy]=useState(false);
  return <details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold">{title}</summary>
    <p className="my-3 text-sm text-slate-600">Import your sourced observations. Values below are input examples, not project evidence. Replace them before saving.</p>
    <textarea aria-label={title} className={inputClass+' min-h-72 font-mono'} value={text} onChange={e=>setText(e.target.value)}/>
    <button className={buttonClass+' mt-3'} disabled={busy} onClick={async()=>{setBusy(true);try{setSaved(await intelligence(path,JSON.parse(text)));setMessage('Validated and saved.');onSaved();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Validate & save evidence</button><p role="status" className="mt-3 text-sm">{message}</p>{saved!==null&&<JsonView value={saved}/>}
  </details>;
}

export function IntelligencePage() {
  const [params] = useSearchParams();
  return <IntelligenceWorkspace key={params.toString()} />;
}
function IntelligenceWorkspace() {
  const [params,setParams]=useSearchParams(); const tab=params.get('tab')||'documents';
  const {data:projects=[],error:projectError}=useQuery({queryKey:['intelligence-projects'],networkMode:'always',queryFn:async()=>{try{const p=await intelligence<any[]>('/projects');localStorage.setItem('field-projects',JSON.stringify(p));return p;}catch(e){const cached=localStorage.getItem('field-projects');if(!navigator.onLine&&cached)return JSON.parse(cached);throw e;}}});
  const [selectedPid,setPid]=useState(Number(params.get('project_id'))||0);
  const pid=selectedPid||projects[0]?.id||0;
  const [revision,setRevision]=useState(0); const reload=()=>setRevision(v=>v+1);
  const {data:status}=useQuery({queryKey:['integration-status',revision],queryFn:()=>intelligence('/status')});
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>(null);
  const run=async(fn:()=>Promise<any>)=>{setBusy(true);setMessage('');try{const value=await fn();setResult(value);reload();return value;}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const {data:documents=[]}=useQuery({queryKey:['documents',pid,revision],queryFn:()=>intelligence<any[]>('/documents/'+pid),enabled:!!pid&&tab==='documents'});
  const {data:satellites=[]}=useQuery({queryKey:['satellite',pid,revision],queryFn:()=>intelligence<any[]>('/satellite/'+pid),enabled:!!pid&&tab==='satellite'});
  const {data:bounds,error:boundsError}=useQuery({queryKey:['uncertainty',pid,revision],queryFn:()=>intelligence('/uncertainty/'+pid),enabled:!!pid&&tab==='uncertainty'});
  const {data:contractors=[]}=useQuery({queryKey:['contractors',revision],queryFn:()=>intelligence<any[]>('/contractors'),enabled:tab==='contractors'});
  const {data:dispatches=[]}=useQuery({queryKey:['dispatch',revision],queryFn:()=>intelligence<any[]>('/dispatch'),enabled:tab==='dispatch'});
  const {data:inspections=[]}=useQuery({queryKey:['inspections',pid,revision],queryFn:()=>intelligence<any[]>('/inspections/'+pid),enabled:!!pid&&tab==='field'});
  const [askPortfolio,setAskPortfolio]=useState(false);const [query,setQuery]=useState('');const [language,setLanguage]=useState('en-IN');const [docFile,setDocFile]=useState<File|null>(null);
  const [shocks,setShocks]=useState({steel:0,cement:0,bitumen:0,diesel:0,rain_days:0,remaining_fraction:1,productivity_loss:.5});
  const [portfolio,setPortfolio]=useState(false);const [channel,setChannel]=useState('telegram');const [intervention,setIntervention]=useState('');
  const [note,setNote]=useState('');const [photo,setPhoto]=useState<File|null>(null);const [captureTime,setCaptureTime]=useState('');
  const [gps,setGps]=useState<GeolocationPosition|null>(null);const [pending,setPending]=useState<any[]>([]);const [receipts,setReceipts]=useState<any[]>([]);const queued=pending.length;const [compare,setCompare]=useState(50);
  useEffect(()=>{getQueue().then(setPending).catch(e=>setMessage('Offline storage: '+String(e)));getReceipts().then(setReceipts).catch(()=>{});},[revision]);
  useEffect(()=>{const sync=()=>{syncQueue().then(r=>{setMessage(`${r.sent} inspection(s) synced. ${r.errors.join(' ')}`);reload();}).catch(e=>setMessage(String(e)));};window.addEventListener('online',sync);return()=>window.removeEventListener('online',sync);},[]);
  const [key,setKey]=useState(sessionStorage.getItem('operator-key')||'');
  const recognize=()=>{
    const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;
    if(!Speech){setMessage('Speech recognition is unavailable in this browser. You can type in English or Hindi.');return;}
    const r=new Speech();r.lang=language;r.onresult=(e:any)=>{const spoken=e.results[0][0].transcript;setQuery(spoken);run(()=>intelligence('/ask',{query:spoken,project_id:askPortfolio?null:pid,language}));};r.onerror=(e:any)=>setMessage('Microphone: '+e.error);r.start();
  };
  const speak=()=>{if(!window.speechSynthesis){setMessage('Speech playback is unavailable.');return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(result.summary);u.lang=language;window.speechSynthesis.speak(u);};
  return <div className="mx-auto max-w-7xl space-y-6 pb-12">
    {!navigator.onLine&&<p className="rounded-xl bg-amber-50 p-3 text-sm">Offline mode · cached project directory · inspections stay on this device until synced.</p>}
    <header className="rounded-2xl bg-gradient-to-br from-slate-900 to-blue-900 p-6 text-white"><div className="text-xs font-bold uppercase tracking-widest text-blue-200">PAIMANA / Intelligence workspace</div><h1 className="mt-2 text-3xl font-bold">Evidence to action</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-blue-100">Inspect the source, explore cost and climate exposure, and record decisions. Every forecast and verification shows its evidence and limitations.</p></header>
    <nav aria-label="Intelligence features" className="flex flex-wrap gap-2">{sections.map(([id,name,Icon])=><button key={id} onClick={()=>setParams({tab:id,...(pid?{project_id:String(pid)}:{})})} className={'flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold '+(tab===id?'bg-blue-700 text-white':'border border-slate-200 bg-white text-slate-600 hover:bg-blue-50')}><Icon size={16}/>{name}</button>)}</nav>
    {projectError&&<p role="alert" className="text-red-700">Cannot load projects: {projectError.message}</p>}
    <label className="block text-sm font-semibold">Project context<select aria-label="Project context" className={inputClass+' mt-2'} value={pid} disabled={busy} onChange={e=>{setPid(Number(e.target.value));setResult(null);setMessage('');}}><option value={0}>Select a project</option>{projects.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {p.state||'Unknown state'} · #{p.id}</option>)}</select></label>
    {message&&<p role="status" className="break-words rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{message}</p>}
    <section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7">
    {tab==='documents'&&<>
      <div><h2 className="text-xl font-bold">Project documents & bilingual copilot</h2><p className="mt-2 text-sm text-slate-500">{status?.gemini?'Gemini with retrieved document evidence':'Local evidence retrieval; configure Gemini for generative answers'}. Document contents are sent to Gemini only when the provider is configured and you ask a question.</p></div>
      <div className="flex flex-wrap items-end gap-3"><label className="grow text-sm">DPR, contract or audit (text PDF / UTF-8, up to 8 MB)<input type="file" accept=".pdf,.txt" className={inputClass+' mt-2'} onChange={e=>setDocFile(e.target.files?.[0]||null)}/></label><button disabled={busy||!pid||!docFile} className={buttonClass} onClick={()=>run(async()=>intelligence('/documents',{project_id:pid,name:docFile!.name,mime:docFile!.name.toLowerCase().endsWith('.pdf')?'application/pdf':'text/plain',content_base64:await encodeFile(docFile!)}))}>Upload document</button></div>
      <div className="flex flex-wrap gap-2">{documents.map(d=><span key={d.id} className="rounded-lg bg-blue-50 px-3 py-2 text-xs">{d.name} · {d.pages.length} pages {d.text_extraction==='requires_multimodal_or_ocr'?'· scanned: Gemini or OCR needed':''}</span>)}{!documents.length&&<p className="text-sm text-slate-500">No documents for this project yet.</p>}</div>
      <label className="block text-sm">Response language<select aria-label="Response language" className={inputClass+' mt-2'} value={language} onChange={e=>setLanguage(e.target.value)}><option value="en-IN">English</option><option value="hi-IN">हिन्दी</option></select></label>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={askPortfolio} onChange={e=>setAskPortfolio(e.target.checked)}/>Search the full portfolio instead of the selected project</label>
      <textarea className={inputClass+' min-h-28'} aria-label="Ask about this project" placeholder="What evidence explains this project's delay?" value={query} onChange={e=>setQuery(e.target.value)}/>
      <div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={busy||!pid||query.trim().length<2} onClick={()=>run(()=>intelligence('/ask',{query,project_id:askPortfolio?null:pid,language}))}>{busy?'Reading evidence…':'Ask copilot'}</button><button className="flex items-center gap-2 rounded-xl border px-4 py-2" onClick={recognize}><Mic size={16}/>Dictate</button>{result?.summary&&<button className="rounded-xl border px-4 py-2" onClick={speak}>Read briefing aloud</button>}</div>
      <LiveVoice projectId={pid} language={language} configured={Boolean(status?.live_audio)}/>
      {result?.summary&&<article className="space-y-4 rounded-xl bg-blue-50 p-5"><span className="text-xs font-bold text-blue-700">{result.provider}</span><p className="whitespace-pre-wrap leading-7">{result.summary}</p>{result.citations?.map((c:any,i:number)=><blockquote key={i} className="border-l-2 border-blue-500 pl-4 text-sm"><strong>{c.name} · page {c.page}</strong><p className="mt-1 whitespace-pre-wrap">{c.text}</p></blockquote>)}{result.projects?.length>0&&<ExpandableChartCard title="Matched project risk" subtitle={`${result.total_matches} matches; showing up to 30 recorded risk scores`}><ResponsiveContainer><BarChart data={result.projects}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="id"/><YAxis domain={[0,1]}/><Tooltip/><Bar dataKey="risk" fill="#1d4ed8"/></BarChart></ResponsiveContainer></ExpandableChartCard>}{result.filters&&<p className="text-xs text-slate-500">Applied filters: {JSON.stringify(result.filters)}</p>}{result.projects?.map((p:any)=><Link key={p.id} className="block text-blue-700 underline" to={'/projects/'+p.id}>{p.name}</Link>)}</article>}
    </>}
    {tab==='twin'&&<>
      <h2 className="text-xl font-bold">Commodity & climate stress twin</h2><p className="text-sm text-slate-500">Transparent sector BOM assumptions. This estimates exposure; it does not establish exact contractual liability.</p>
      <div className="grid gap-5 sm:grid-cols-2">{Object.entries(shocks).map(([name,value])=><label key={name} className="text-sm capitalize">{name.replaceAll('_',' ')} {['steel','cement','bitumen','diesel'].includes(name)?'change (%)':''}<input type="number" step={name.includes('fraction')||name.includes('loss')?'.05':'1'} min={['steel','cement','bitumen','diesel'].includes(name)?-100:0} max={name.includes('fraction')||name.includes('loss')?1:name==='rain_days'?366:1000} className={inputClass+' mt-2'} value={value} onChange={e=>setShocks({...shocks,[name]:Number(e.target.value)})}/></label>)}</div>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={portfolio} onChange={e=>setPortfolio(e.target.checked)}/>Apply assumptions across the full portfolio</label>
      <button disabled={busy||(!portfolio&&!pid)} className={buttonClass} onClick={()=>run(()=>intelligence('/twin',{...shocks,project_id:portfolio?null:pid}))}>Calculate exposure</button>
      {result?.projects&&<><div className="rounded-xl bg-blue-50 p-5"><p className="text-sm">Estimated incremental cost</p><strong className="text-3xl text-blue-800">₹{result.total_cost_increase_cr.toLocaleString('en-IN',{maximumFractionDigits:2})} Cr</strong><p className="mt-2 text-xs">{result.source}</p></div><div className="max-h-96 overflow-auto">{result.projects.map((p:any)=><div key={p.project_id} className="border-b py-3 text-sm"><strong>{p.name}</strong><p>₹{p.cost_increase_cr.toFixed(2)} Cr · {p.schedule_buffer_days} rainfall buffer days</p></div>)}</div></>}
      <EvidenceImport title="Import dated commodity / rainfall observation" path="/market" initial={{as_of:today,source:'Replace with published source and index series',region:'Maharashtra',steel:100,cement:100,bitumen:100,diesel:100,rain_days:0}} onSaved={reload}/>
      <button className="text-sm text-blue-700 underline" onClick={()=>run(()=>intelligence('/market'))}>View market observations and IDs</button>
      {Array.isArray(result)&&<JsonView value={result}/>}
      <button className={buttonClass} disabled={busy} onClick={()=>run(()=>intelligence('/market/refresh',{}))}>Refresh configured market feed</button><MarketComparison pid={pid} onRun={run}/>
    </>}
    {tab==='satellite'&&<>
      <h2 className="text-xl font-bold">Satellite ground-truth review</h2><p className="text-sm text-slate-500">Compare sourced, co-registered surface reflectance observations. Optical indices cannot prove completion or fraud. Cloudy observations are inconclusive.</p>
      <EvidenceImport key={'satellite'+pid} title="Import before / after observations" path="/satellite" initial={{project_id:pid,source:'Replace with processing method and source',claimed_progress_pct:0,before:{date:'2026-01-01',sensor:'Sentinel-2',scene_id:'replace-before-scene',red:.2,nir:.4,swir:.3,cloud_pct:0},after:{date:'2026-02-01',sensor:'Sentinel-2',scene_id:'replace-after-scene',red:.2,nir:.4,swir:.3,cloud_pct:0}}} onSaved={reload}/>
      <CatalogSearch onRun={run}/><EvidenceImport key={'compute'+pid} title="Compute indices from real satellite scenes" path="/satellite/compute" initial={{project_id:pid,collection:'sentinel-2-l2a',before_scene_id:'replace-from-catalog',after_scene_id:'replace-from-catalog',claimed_progress_pct:0}} onSaved={reload}/>{result?.scenes&&<JsonView value={result}/>}<EvidenceImport key={'radar'+pid} title="Compare Sentinel-1 radar observations (account required)" path="/satellite/radar" initial={{project_id:pid,before_scene_id:'replace-from-rtc-catalog',after_scene_id:'replace-from-rtc-catalog',polarization:'vv',claimed_progress_pct:0}} onSaved={reload}/>
      {!satellites.length&&<p className="text-sm text-slate-500">No satellite evidence imported.</p>}
      {satellites.map(s=><article key={s.id} className="space-y-3 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{s.before.date} → {s.after.date}</strong><span className="rounded bg-amber-50 px-3 py-1 text-sm">{s.status.replaceAll('_',' ')}</span></div><p className="text-sm">NDVI: {s.ndvi.map((v:number|null)=>v===null?'not optical':v.toFixed(4)).join(' → ')} · NDBI delta: {s.ndbi_delta?.toFixed(4)??'unavailable'} · SAR delta: {s.sar_delta_db??'not supplied'}</p>
      {(s.before.image_data||s.before.image_url)&&(s.after.image_data||s.after.image_url)&&<><div className="relative h-72 overflow-hidden rounded-xl"><img className="absolute h-full w-full object-contain" src={s.after.image_data||s.after.image_url} alt="After satellite observation" referrerPolicy="no-referrer"/><img className="absolute h-full w-full object-contain" style={{clipPath:`inset(0 ${100-compare}% 0 0)`}} src={s.before.image_data||s.before.image_url} alt="Before satellite observation" referrerPolicy="no-referrer"/></div><label className="text-sm">Before / after comparison<input aria-label="Satellite before after comparison" className="w-full" type="range" min="0" max="100" value={compare} onChange={e=>setCompare(Number(e.target.value))}/></label></>}
      <p className="text-xs text-slate-500">Source: {s.source}. {s.limitation}</p></article>)}
    </>}
    {tab==='uncertainty'&&<>
      <h2 className="text-xl font-bold">Calibrated prediction intervals</h2><p className="text-sm text-slate-500">90% marginal prediction intervals from held-out residuals for the same model. Cohort survival accounts for right-censored observations.</p>
      {boundsError&&<p role="alert">{boundsError.message}</p>}
      {bounds?.status==='unavailable'&&<p className="rounded-xl bg-amber-50 p-4">{bounds.reason}</p>}
      {bounds?.interval&&<><div className="rounded-xl bg-blue-50 p-5"><p>Predicted delay (days)</p><p className="text-3xl font-bold">{bounds.interval.point.toFixed(0)} <span className="text-lg font-normal">[{bounds.interval.lower.toFixed(0)} – {bounds.interval.upper.toFixed(0)}]</span></p><p className="mt-2 text-sm">{bounds.interval.calibration_count} calibration outcomes · {bounds.model_version}</p><p className="mt-2 text-xs">{bounds.interval.limitation}</p>{bounds.completion_dates&&<p className="mt-3 text-sm">Completion: {bounds.completion_dates.point} [{bounds.completion_dates.lower} – {bounds.completion_dates.upper}]</p>}<p className="mt-3 text-sm">Cohort probability of completion by {bounds.fy_end}: {bounds.cohort_probability_by_fy_end===null?'Unavailable':(bounds.cohort_probability_by_fy_end*100).toFixed(1)+'%'}</p><p className="text-xs">{bounds.fy_probability_note}</p></div>{bounds.survival_curve.length>0&&<div><h3 className="mb-3 font-semibold">{bounds.survival_label}</h3><div className="h-72"><ResponsiveContainer><AreaChart data={bounds.survival_curve}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis domain={[0,1]}/><Tooltip/><Area type="stepAfter" dataKey="completion_probability" stroke="#1d4ed8" fill="#bfdbfe"/></AreaChart></ResponsiveContainer></div></div>}</>}
      <EvidenceImport key={'inference'+pid} title="Run saved ML models with observed project features" path="/model/predict" initial={{project_id:pid,features:{project_original_budget_cr:null,project_planned_duration_days:null,sector_historical_overrun_avg:null,sector_historical_delay_avg_months:null,ministry_active_projects_count:null,ministry_avg_completion_rate:null,cost_expenditure_ratio:null,cost_acceleration_mom:null,schedule_remaining_days:null,schedule_elapsed_pct:null,progress_physical_pct:null,progress_gap_pct:null,progress_velocity_mom:null,progress_trend_3m:null,progress_trend_6m:null,milestone_slippage_rate:null,temporal_project_age_months:null,historical_contractor_delay_score:null}}} onSaved={reload}/>
      <EvidenceImport title="Import held-out calibration outcomes" path="/calibration" initial={{model_version:'replace-with-persisted-model-version',target:'delay_days',source:'Replace with independent held-out evaluation dataset',held_out:true,pairs:[],survival:[]}} onSaved={reload}/>
    </>}
    {tab==='contractors'&&<>
      <h2 className="text-xl font-bold">InfraScore · cross-ministry delivery</h2><p className="text-sm text-slate-500">Verified identities and sourced delivery records are required. Scores need at least three projects; agencies are not silently treated as contractors.</p>
      {!contractors.length&&<p className="rounded-xl bg-slate-50 p-4 text-sm">No contractor evidence yet.</p>}
      <div className="grid gap-4 md:grid-cols-2">{contractors.map(c=><article key={c.contractor_id} className="rounded-xl border p-5"><h3 className="font-bold">{c.name}</h3><p className="mt-3 text-3xl font-bold text-blue-700">{c.score??'Insufficient sample'}{c.score!==null&&<span className="text-sm"> / 100</span>}</p><p className="mt-2 text-sm">{c.project_count} projects · {c.on_time_index}% on-time milestones</p><p className="text-sm">{c.claims_per_1000_cr} claims / ₹1,000 Cr · Payment: {c.payment_days??'unknown'} days</p><p className="mt-2 text-sm text-amber-800">{c.critical_packages} packages delayed over 180 days</p><p className="mt-2 text-xs text-slate-500">{c.ministries.join(' · ')}<br/>{c.score_basis}</p></article>)}</div>
      <EvidenceImport key={'contractor'+pid} title="Register contractor delivery record" path="/contractors" initial={{project_id:pid,contractor_id:'replace-verified-identity',name:'Contractor legal name',source:'Replace with source record',as_of:today,milestone_count:1,on_time_count:0,arbitration_claims:0,work_value_cr:1,payment_days:null,delay_days:0}} onSaved={reload}/>
    </>}
    {tab==='field'&&<>
      <ProjectRecords key={pid} projectId={pid}/>
      <h2 className="text-xl font-bold">Offline field inspection</h2><p className="text-sm text-slate-500">Photos are hashed and queued on this device until synced. GPS and capture time are device-reported; hashes do not prove photo authenticity. Open this page online once before using it offline.</p>
      <div className="rounded-xl bg-blue-50 p-4"><strong>{queued} inspection(s) awaiting sync</strong><button disabled={busy} className={buttonClass+' ml-3'} onClick={()=>run(async()=>{const r=await syncQueue();if(r.errors.length)setMessage(r.errors.join(' '));return r;})}>Sync now</button></div>
      {pending.length>0&&<div className="space-y-3"><h3 className="font-semibold">Saved on this device</h3>{pending.map(item=><article key={item.client_id} className="rounded-xl border p-4 text-sm"><strong>{String(item.note)} · Project #{String(item.project_id)}</strong><p className="mt-1 text-xs text-slate-500">{String(item.captured_at)} · {item._sync?.paused?'Paused':'Pending'} · {item._sync?.attempts||0} attempts</p>{item._sync?.lastError&&<p className="mt-2 text-amber-800">{item._sync.lastError}</p>}<button disabled={busy} className="mt-2 text-blue-700 underline" onClick={()=>run(()=>pauseInspection(item.client_id,!item._sync?.paused))}>{item._sync?.paused?'Resume upload':'Pause upload'}</button></article>)}<button className="text-sm text-blue-700 underline" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(pending,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='paimana-private-inspection-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Download private backup (photos and GPS included)</button></div>}
      {receipts.length>0&&<details className="rounded-xl border p-4"><summary className="font-semibold">{receipts.length} saved sync receipts</summary>{receipts.map(r=><p key={r.client_id} className="mt-3 break-all text-xs">{r.synced_at} · Receipt #{String(r.receipt.id)} · {String(r.receipt.evidence_sha256)}</p>)}</details>}
      <label className="block text-sm">Milestone notes<textarea className={inputClass+' mt-2'} value={note} onChange={e=>setNote(e.target.value)}/></label>
      <label className="block text-sm">Capture photo<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className={inputClass+' mt-2'} onChange={e=>{setPhoto(e.target.files?.[0]||null);setCaptureTime(new Date().toISOString());setGps(null);}}/></label>
      <button className="rounded-xl border px-4 py-2 text-sm" onClick={()=>{if(!navigator.geolocation){setMessage('Geolocation unavailable');return;}navigator.geolocation.getCurrentPosition(setGps,e=>setMessage(e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0});}}>Get current GPS location</button>
      {gps&&<p className="text-sm">{gps.coords.latitude.toFixed(6)}, {gps.coords.longitude.toFixed(6)} · accuracy {gps.coords.accuracy.toFixed(0)} m</p>}
      <button disabled={busy||!pid||!photo||!gps||!note.trim()} className={buttonClass+' block'} onClick={()=>run(async()=>{
        if(!gps||Date.now()-gps.timestamp>300000)throw new Error('Refresh GPS before saving (five minute maximum).');
        if(gps.coords.accuracy>100)throw new Error('GPS accuracy must be within 100 metres. Try outdoors.');
        const raw=await photo!.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',raw))).map(x=>x.toString(16).padStart(2,'0')).join('');
        await queueInspection({project_id:pid,client_id:crypto.randomUUID(),latitude:gps.coords.latitude,longitude:gps.coords.longitude,accuracy_m:gps.coords.accuracy,captured_at:captureTime,note,photo_base64:await encodeFile(photo!),photo_sha256:hash});
        setNote('');setPhoto(null);setGps(null);setMessage('Saved on this device.');if(navigator.onLine){const r=await syncQueue();setMessage(`${r.sent} synced. ${r.errors.join(' ')}`);}return {queued:true};
      })}>Save inspection on device</button>
      <label className="block text-sm">Restore a private inspection backup (restored uploads start paused)<input type="file" accept="application/json,.json" className={inputClass+' mt-2'} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{if(file.size>50_000_000)throw new Error('Backup exceeds 50 MB.');const restored=await restoreQueueBackup(JSON.parse(await file.text()));setMessage(`${restored.restored} restored, ${restored.skipped} already present. Resume uploads after review.`);return restored;});}}/></label>
      <EvidenceImport key={'boundary'+pid} title="Register project boundary (longitude, latitude polygon)" path="/boundaries" initial={{project_id:pid,source:'Replace with surveyed boundary source',ring:[]}} onSaved={reload}/>
      {inspections.map(i=><article key={i.id} className="rounded-xl border p-4 text-sm"><strong>{i.note}</strong><p className="mt-2">Captured: {i.captured_at} · Received: {i.received_at}</p><p className="break-all text-xs">Receipt: {i.evidence_sha256}</p><p className="mt-2 text-slate-500">{i.verification}</p></article>)}
    </>}
    {tab==='dispatch'&&<>
      <h2 className="text-xl font-bold">Executive escalation dispatch</h2><p className="text-sm text-slate-500">Creates a real outbound message when the provider is configured. Approval links expire in 24 hours and accept one decision. Link previews never approve an action.</p>
      <label className="block text-sm">Intervention ID<input className={inputClass+' mt-2'} type="number" min="1" value={intervention} onChange={e=>setIntervention(e.target.value)}/></label><Link className="text-sm text-blue-700 underline" to="/interventions">Find an intervention in Risk & Alerts</Link>
      <label className="block text-sm">Delivery channel<select className={inputClass+' mt-2'} value={channel} onChange={e=>setChannel(e.target.value)}>{['telegram','whatsapp','email','slack'].map(c=><option key={c}>{c}</option>)}</select></label>
      <button disabled={busy||!intervention} className={buttonClass} onClick={()=>run(()=>intelligence('/dispatch',{intervention_id:Number(intervention),channel,idempotency_key:crypto.randomUUID()}))}>Send executive escalation</button>
      {result&&<JsonView value={result}/>}<h3 className="font-semibold">Delivery audit</h3>{dispatches.map(d=><div key={d.id} className="rounded-xl border p-4 text-sm">Intervention #{d.intervention_id} · Tier {d.tier} · {d.channel}<p className="font-semibold">{d.status}</p><p>{d.error}</p></div>)}
    </>}
    {tab==='reports'&&<><h2 className="text-xl font-bold">Ministry executive dossier</h2><p className="text-sm text-slate-500">Export the selected project's financial summary, open alerts, interventions, calibrated forecast availability and document source hashes.</p><a className={buttonClass+' inline-flex items-center gap-2'} href={intelligenceBase+'/dossier/'+pid}><Download size={16}/>Download project PDF</a></>}
    {tab==='settings'&&<><h2 className="text-xl font-bold">Provider readiness</h2><p className="text-sm text-slate-500">Provider credentials belong in the backend environment. This page never exposes them. Missing credentials do not activate simulated success.</p><JsonView value={status}/><label className="block text-sm">Operator API key (this browser session only)<input type="password" autoComplete="off" className={inputClass+' mt-2'} value={key} onChange={e=>setKey(e.target.value)}/></label><button className={buttonClass} onClick={()=>{sessionStorage.setItem('operator-key',key);setMessage('Session key saved.');}}>Save session key</button></>}
    </section>
  </div>;
}
function MarketComparison({pid,onRun}:{pid:number;onRun:(fn:()=>Promise<any>)=>Promise<any>}){const [base,setBase]=useState('');const [current,setCurrent]=useState('');return <div className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">Compare sourced index observations</h3><div className="grid gap-3 sm:grid-cols-2"><input aria-label="Baseline observation ID" placeholder="Baseline observation ID" type="number" className={inputClass} value={base} onChange={e=>setBase(e.target.value)}/><input aria-label="Current observation ID" placeholder="Current observation ID" type="number" className={inputClass} value={current} onChange={e=>setCurrent(e.target.value)}/></div><button className={buttonClass} disabled={!base||!current||!pid} onClick={()=>onRun(()=>intelligence('/twin',{project_id:pid,baseline_id:Number(base),current_id:Number(current)}))}>Run index-coupled scenario</button></div>;}
function CatalogSearch({onRun}:{onRun:(fn:()=>Promise<any>)=>Promise<any>}){const [value,setValue]=useState(JSON.stringify({west:72,south:19,east:72.1,north:19.1,start:'2026-01-01',end:'2026-02-01',collection:'sentinel-2-l2a'},null,2));return <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Search open Sentinel / Landsat catalog</summary><textarea aria-label="Catalog bounding box and dates" className={inputClass+' mt-3 min-h-48 font-mono'} value={value} onChange={e=>setValue(e.target.value)}/><button className={buttonClass+' mt-3'} onClick={()=>onRun(async()=>intelligence('/satellite/search',JSON.parse(value)))}>Find source scenes</button></details>;}
